2024-05-14 17:27:07,880 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:50]
2024-05-14 17:27:41,210 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:50]
2024-05-14 17:32:01,855 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:50]
2024-05-14 17:34:03,500 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:50]
2024-05-14 17:40:12,051 ERROR: Exception on /register [POST] [in /Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/routes.py", line 118, in register
    user.set_password(form.password.data)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/models.py", line 29, in set_password
    self.password_hash = generate_password_hash(password)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/werkzeug/security.py", line 105, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/werkzeug/security.py", line 43, in _hash_internal
    hashlib.scrypt(
AttributeError: module 'hashlib' has no attribute 'scrypt'
2024-05-14 17:43:08,543 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:50]
2024-05-14 17:47:47,051 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:50]
2024-05-14 17:48:14,511 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:50]
2024-05-14 17:50:30,530 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:50]
2024-05-14 17:51:59,431 ERROR: Exception on /register [POST] [in /Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/routes.py", line 118, in register
    user.set_password(form.password.data)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/models.py", line 29, in set_password
    self.password_hash = generate_password_hash(password)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/werkzeug/security.py", line 105, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/werkzeug/security.py", line 43, in _hash_internal
    hashlib.scrypt(
AttributeError: module 'hashlib' has no attribute 'scrypt'
2024-05-14 17:56:36,364 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:50]
2024-05-14 17:56:51,819 ERROR: Exception on /register [POST] [in /Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/routes.py", line 118, in register
    user.set_password(form.password.data)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/models.py", line 29, in set_password
    self.password_hash = generate_password_hash(password)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/werkzeug/security.py", line 105, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/werkzeug/security.py", line 43, in _hash_internal
    hashlib.scrypt(
AttributeError: module 'hashlib' has no attribute 'scrypt'
2024-05-14 17:57:29,667 ERROR: Exception on /register [POST] [in /Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/routes.py", line 118, in register
    user.set_password(form.password.data)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/models.py", line 29, in set_password
    self.password_hash = generate_password_hash(password)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/werkzeug/security.py", line 105, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/werkzeug/security.py", line 43, in _hash_internal
    hashlib.scrypt(
AttributeError: module 'hashlib' has no attribute 'scrypt'
2024-05-14 18:07:37,669 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:50]
2024-05-14 18:07:54,101 ERROR: Exception on /register [POST] [in /Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/routes.py", line 118, in register
    user.set_password(form.password.data)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/models.py", line 29, in set_password
    self.password_hash = generate_password_hash(password)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/werkzeug/security.py", line 105, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/werkzeug/security.py", line 43, in _hash_internal
    hashlib.scrypt(
AttributeError: module 'hashlib' has no attribute 'scrypt'
2024-05-14 18:42:48,876 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:50]
2024-05-15 09:25:49,472 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:50]
