2024-05-08 23:13:39,872 ERROR: Exception on /index [GET] [in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/indragultom/GroupProject/app/routes.py", line 30, in index
    return render_template('index.html', posts=all_posts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/indragultom/GroupProject/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/indragultom/GroupProject/app/templates/base.html", line 104, in top-level template code
    {% block content %}
  File "/Users/indragultom/GroupProject/app/templates/index.html", line 79, in block 'content'
    <form action="{{ url_for('guess_price', post_id=post.id) }}" method="post">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/werkzeug/routing/map.py", line 926, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'guess_price' with values ['post_id']. Did you mean 'edit_profile' instead?
2024-05-08 23:14:27,794 INFO: ValueCheck startup [in /Users/indragultom/GroupProject/app/__init__.py:52]
2024-05-08 23:20:04,573 INFO: ValueCheck startup [in /Users/indragultom/GroupProject/app/__init__.py:52]
2024-05-08 23:22:54,906 INFO: ValueCheck startup [in /Users/indragultom/GroupProject/app/__init__.py:52]
2024-05-08 23:24:17,225 INFO: ValueCheck startup [in /Users/indragultom/GroupProject/app/__init__.py:52]
2024-05-08 23:26:40,315 INFO: ValueCheck startup [in /Users/indragultom/GroupProject/app/__init__.py:52]
2024-05-08 23:31:20,695 INFO: ValueCheck startup [in /Users/indragultom/GroupProject/app/__init__.py:52]
2024-05-08 23:31:26,388 INFO: ValueCheck startup [in /Users/indragultom/GroupProject/app/__init__.py:52]
2024-05-08 23:32:17,222 INFO: ValueCheck startup [in /Users/indragultom/GroupProject/app/__init__.py:52]
2024-05-09 14:42:11,695 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-09 14:42:39,204 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-09 17:59:38,561 ERROR: Exception on /register [POST] [in /Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/routes.py", line 64, in register
    user.set_password(form.password.data)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/models.py", line 32, in set_password
    self.password_hash = generate_password_hash(password)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/werkzeug/security.py", line 105, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/werkzeug/security.py", line 43, in _hash_internal
    hashlib.scrypt(
AttributeError: module 'hashlib' has no attribute 'scrypt'
2024-05-10 12:35:44,320 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 12:36:14,570 ERROR: Exception on /register [POST] [in /Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/routes.py", line 64, in register
    user.set_password(form.password.data)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/models.py", line 32, in set_password
    self.password_hash = generate_password_hash(password)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/werkzeug/security.py", line 105, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/werkzeug/security.py", line 43, in _hash_internal
    hashlib.scrypt(
AttributeError: module 'hashlib' has no attribute 'scrypt'
2024-05-10 12:40:11,797 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 12:46:45,617 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 12:53:26,445 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 12:55:17,904 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 12:55:20,413 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 12:55:59,297 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 12:56:48,259 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 12:58:57,064 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 12:59:31,128 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:01:32,558 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:02:48,275 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:04:13,175 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:04:33,070 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:05:06,139 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:05:29,850 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:05:54,982 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:06:54,332 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:15:35,881 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
